{"stats": {"errors": 2, "failures": 10, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 12}, "results": [{"classname": "index_test:TestAggregateFunctions", "name": "test_average_hr_per_year", "time": 0.0002429485321044922, "type": "error", "errtype": "builtins.IndexError", "message": "list index out of range", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/yoyothesheep/sql-queries-with-aggregate-functions-lab-data-science/test/index_test.py\", line 46, in test_average_hr_per_year\n    result = cursor.execute(average_hr_per_year()).fetchall()[0][0]\nIndexError: list index out of range\n"}, {"classname": "index_test:TestAggregateFunctions", "name": "test_avg_batting_avg_aliased_as_career_average", "time": 0.0001316070556640625, "type": "error", "errtype": "builtins.IndexError", "message": "list index out of range", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/yoyothesheep/sql-queries-with-aggregate-functions-lab-data-science/test/index_test.py\", line 56, in test_avg_batting_avg_aliased_as_career_average\n    result = cursor.execute(avg_batting_avg_aliased_as_career_average()).fetchall()[0][0]\nIndexError: list index out of range\n"}, {"classname": "index_test:TestAggregateFunctions", "name": "test_least_hr", "time": 0.0003421306610107422, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [(0,)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(0,)\n\n- []\n+ [(0,)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/yoyothesheep/sql-queries-with-aggregate-functions-lab-data-science/test/index_test.py\", line 25, in test_least_hr\n    self.assertEqual(cursor.execute(least_hr()).fetchall(), result)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [(0,)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(0,)\n\n- []\n+ [(0,)]\n"}, {"classname": "index_test:TestAggregateFunctions", "name": "test_most_hr", "time": 0.0002567768096923828, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [(60,)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(60,)\n\n- []\n+ [(60,)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/yoyothesheep/sql-queries-with-aggregate-functions-lab-data-science/test/index_test.py\", line 21, in test_most_hr\n    self.assertEqual(cursor.execute(most_hr()).fetchall(), result)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [(60,)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(60,)\n\n- []\n+ [(60,)]\n"}, {"classname": "index_test:TestAggregateFunctions", "name": "test_select_yr_and_min_hr_with_at_least_100_games", "time": 0.0002472400665283203, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [(1934, 22)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(1934, 22)\n\n- []\n+ [(1934, 22)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/yoyothesheep/sql-queries-with-aggregate-functions-lab-data-science/test/index_test.py\", line 33, in test_select_yr_and_min_hr_with_at_least_100_games\n    self.assertEqual(cursor.execute(select_yr_and_min_hr_with_at_least_100_games()).fetchall(), result)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [(1934, 22)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(1934, 22)\n\n- []\n+ [(1934, 22)]\n"}, {"classname": "index_test:TestAggregateFunctions", "name": "test_total_hr", "time": 0.0002446174621582031, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [(714,)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(714,)\n\n- []\n+ [(714,)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/yoyothesheep/sql-queries-with-aggregate-functions-lab-data-science/test/index_test.py\", line 37, in test_total_hr\n    self.assertEqual(cursor.execute(total_hr()).fetchall(), result)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [(714,)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(714,)\n\n- []\n+ [(714,)]\n"}, {"classname": "index_test:TestAggregateFunctions", "name": "test_total_seasons", "time": 0.00024199485778808594, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [(22,)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(22,)\n\n- []\n+ [(22,)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/yoyothesheep/sql-queries-with-aggregate-functions-lab-data-science/test/index_test.py\", line 13, in test_total_seasons\n    self.assertEqual(cursor.execute(total_seasons()).fetchall(), result)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [(22,)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(22,)\n\n- []\n+ [(22,)]\n"}, {"classname": "index_test:TestAggregateFunctions", "name": "test_total_seasons_with_ny", "time": 0.00023436546325683594, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [(15,)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(15,)\n\n- []\n+ [(15,)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/yoyothesheep/sql-queries-with-aggregate-functions-lab-data-science/test/index_test.py\", line 17, in test_total_seasons_with_ny\n    self.assertEqual(cursor.execute(total_seasons_with_ny()).fetchall(), result)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [(15,)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(15,)\n\n- []\n+ [(15,)]\n"}, {"classname": "index_test:TestAggregateFunctions", "name": "test_total_years_and_hits_per_team", "time": 0.0002815723419189453, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [('BOS', 7, 355), ('NY', 15, 2518)]\n\nSecond list contains 2 additional elements.\nFirst extra element 0:\n('BOS', 7, 355)\n\n- []\n+ [('BOS', 7, 355), ('NY', 15, 2518)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/yoyothesheep/sql-queries-with-aggregate-functions-lab-data-science/test/index_test.py\", line 70, in test_total_years_and_hits_per_team\n    self.assertEqual(cursor.execute(total_years_and_hits_per_team()).fetchall(), result)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [('BOS', 7, 355), ('NY', 15, 2518)]\n\nSecond list contains 2 additional elements.\nFirst extra element 0:\n('BOS', 7, 355)\n\n- []\n+ [('BOS', 7, 355), ('NY', 15, 2518)]\n"}, {"classname": "index_test:TestAggregateFunctions", "name": "test_total_years_and_hr_per_team_ordered_by_hr", "time": 0.00025963783264160156, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [('NY', 15, 659), ('BOS', 7, 55)]\n\nSecond list contains 2 additional elements.\nFirst extra element 0:\n('NY', 15, 659)\n\n- []\n+ [('NY', 15, 659), ('BOS', 7, 55)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/yoyothesheep/sql-queries-with-aggregate-functions-lab-data-science/test/index_test.py\", line 74, in test_total_years_and_hr_per_team_ordered_by_hr\n    self.assertEqual(cursor.execute(total_years_and_hr_per_team_ordered_by_hr()).fetchall(), result)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [('NY', 15, 659), ('BOS', 7, 55)]\n\nSecond list contains 2 additional elements.\nFirst extra element 0:\n('NY', 15, 659)\n\n- []\n+ [('NY', 15, 659), ('BOS', 7, 55)]\n"}, {"classname": "index_test:TestAggregateFunctions", "name": "test_year_and_games_with_least_hr", "time": 0.0002377033233642578, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [(1914, 5)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(1914, 5)\n\n- []\n+ [(1914, 5)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/yoyothesheep/sql-queries-with-aggregate-functions-lab-data-science/test/index_test.py\", line 29, in test_year_and_games_with_least_hr\n    self.assertEqual(cursor.execute(year_and_games_with_least_hr()).fetchall(), result)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [(1914, 5)]\n\nSecond list contains 1 additional elements.\nFirst extra element 0:\n(1914, 5)\n\n- []\n+ [(1914, 5)]\n"}, {"classname": "index_test:TestAggregateFunctions", "name": "test_years_with_on_base_over_300", "time": 0.00046372413635253906, "type": "failure", "errtype": "builtins.AssertionError", "message": "Lists differ: [] != [(1920, 322), (1921, 349), (1923, 375), (1[70 chars]327)]\n\nSecond list contains 9 additional elements.\nFirst extra element 0:\n(1920, 322)\n\n- []\n+ [(1920, 322),\n+  (1921, 349),\n+  (1923, 375),\n+  (1924, 342),\n+  (1926, 328),\n+  (1927, 329),\n+  (1928, 310),\n+  (1930, 322),\n+  (1931, 327)]", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/yoyothesheep/sql-queries-with-aggregate-functions-lab-data-science/test/index_test.py\", line 78, in test_years_with_on_base_over_300\n    self.assertEqual(cursor.execute(years_with_on_base_over_300()).fetchall(), result)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: Lists differ: [] != [(1920, 322), (1921, 349), (1923, 375), (1[70 chars]327)]\n\nSecond list contains 9 additional elements.\nFirst extra element 0:\n(1920, 322)\n\n- []\n+ [(1920, 322),\n+  (1921, 349),\n+  (1923, 375),\n+  (1924, 342),\n+  (1926, 328),\n+  (1927, 329),\n+  (1928, 310),\n+  (1930, 322),\n+  (1931, 327)]\n"}]}